<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ZW8IO3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ZW8IO3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2ZW8IO3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2ZW8IO3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2ZW8IO3\App_KernelDevDebugContainer([
    'container.build_hash' => '2ZW8IO3',
    'container.build_id' => '5628266a',
    'container.build_time' => 1638893096,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ZW8IO3');
