<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Rlni1S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Rlni1S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Rlni1S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Rlni1S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0Rlni1S\App_KernelDevDebugContainer([
    'container.build_hash' => '0Rlni1S',
    'container.build_id' => '306fc1e6',
    'container.build_time' => 1637013784,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Rlni1S');
