<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHEuX085\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHEuX085/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHEuX085.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHEuX085\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHEuX085\App_KernelDevDebugContainer([
    'container.build_hash' => 'HEuX085',
    'container.build_id' => '5039654c',
    'container.build_time' => 1637015769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHEuX085');
